config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'admin/', class_name: 'Admin::User', controllers: {sessions: 'admin/sessions'}
  root to: 'admin/orders#index'
  namespace :admin do

    resources :products do
      resources :product_properties
      resources :variants
    end
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :complete
      end
    end
    resources :banners
    resources :option_types
    resources :prototypes do
      member do
        get :get_property_names
      end
    end
    resources :feedbacks

    require 'sidekiq/web'
    require 'sidekiq-status/web'
    authenticate :admin_user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount API, at: '/api'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_one :icon, as: :attachable, dependent: :destroy, class_name: 'Image', inverse_of: :attachable

  accepts_nested_attributes_for :icon
end

app/controllers/admin/brands_controller.rb
module Admin
  class BrandsController < AdminController
    before_action :set_brand, only: [:edit, :update, :destroy]
    def index
      @brands = Brand.all
    end

    def new
      set_aliyun_upload
      @brand = Brand.new
    end

    def create
      @brand = Brand.new(brand_params)
      @brand.save
      redirect_to admin_brands_path
    end

    def edit
      set_aliyun_upload
    end

    def update
      @brand.update(brand_params)
      redirect_to admin_brands_path
    end

    def destroy
      @brand.destroy
      redirect_to admin_brands_path
    end

    private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params[:brand].permit!
    end
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/views/admin/brands/_brand.html.erb
<tr>
  <td><%= brand.name %></td>
  <td><%= brand.position %></td>
  <td>
    <%= link_to '编辑', edit_admin_brand_path(brand) %>
    <%= link_to '删除', admin_brand_path(brand), method: :delete %>
  </td>
</tr>

app/views/admin/brands/_form.html.erb
<%= form_for [:admin, @brand] do |f| %>
  <div class="form-group">
    <label>品牌名称</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>品牌图标</label>
    <input type="file" id="upload" />
  </div>
  <div class="form-group">
    <label>排序</label>
    <%= f.text_field :position, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-default">确定保存</button>
  <button type="reset" class="btn btn-default">取消</button>
<% end %>

app/views/admin/brands/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">编辑品牌</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= render 'form' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/brands/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <h1 class="page-header">品牌列表
      <a href="<%= new_admin_brand_path %>" style="float: right; padding-right: 15px;"><button type="button" class="btn btn-primary btn-lg">添加品牌</button></a>
    </h1>

  </div>
  <!-- /.col-lg-12 -->
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <!-- /.panel-heading -->
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="products">
            <thead>
            <tr>
              <th>名称</th>
              <th>排序</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: 'brand', collection: @brands %>
            </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->

</div>

app/views/admin/brands/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">添加品牌</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= render 'form' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->