config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'admin/', class_name: 'Admin::User', controllers: {sessions: 'admin/sessions'}
  root to: 'admin/orders#index'
  namespace :admin do

    resources :products do
      resources :product_properties
      resources :variants
    end
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :complete
      end
    end
    resources :banners
    resources :option_types
    resources :prototypes do
      member do
        get :get_property_names
      end
    end
    resources :feedbacks

    require 'sidekiq/web'
    require 'sidekiq-status/web'
    authenticate :admin_user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount API, at: '/api'
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product, touch: true, class_name: 'Product', inverse_of: :variants
  delegate :name, :name=, :description, to: :product

  before_destroy :ensure_no_line_items

  has_many :images, as: :attachable, dependent: :destroy, class_name: 'Image', inverse_of: :attachable

  has_many :option_value_variants
  has_many :option_values, through: :option_value_variants
  # validates :option_values, presence: true, unless: :is_master?

  def product
    Product.unscoped { super }
  end

  def options=(options = {})
    options.each do |option|
      set_option_value(option[:name], option[:value])
    end
  end

  def set_option_value(opt_name, opt_value)
    # no option values on master
    return if is_master

    option_type = OptionType.where(name: opt_name).first_or_initialize do |o|
      o.presentation = opt_name
      o.save!
    end

    current_value = option_values.detect { |o| o.option_type.name == opt_name }

    if current_value.nil?
      # then we have to check to make sure that the product has the option type
      unless product.option_types.include? option_type
        product.option_types << option_type
      end
    else
      return if current_value.name == opt_value
      option_values.delete(current_value)
    end

    option_value = OptionValue.where(option_type_id: option_type.id, name: opt_value).first_or_initialize do |o|
      o.presentation = opt_value
      o.save!
    end

    option_values << option_value
    save
  end

  def option_value(opt_name)
    option_values.detect { |o| o.option_type.name == opt_name }.try(:presentation)
  end

  def options_text
    values = option_values.sort do |a, b|
      a.option_type.position <=> b.option_type.position
    end

    values.to_a.map! do |ov|
      # "#{ov.option_type.presentation}: #{ov.presentation}"
      "#{ov.presentation}"
    end

    values.to_sentence(words_connector: '；', two_words_connector: '；')
  end

  private
  def ensure_no_line_items
    if line_items.any?
      errors.add(:base, :cannot_destroy_if_attached_to_line_items)
      throw(:abort)
    end
  end
end

app/controllers/admin/variants_controller.rb
module Admin
  class VariantsController < AdminController
    before_action :set_product
    before_action :set_variant, only: [:edit, :update, :destroy]

    def index
      @variants = @product.variants
    end

    def new
      @variant = @product.variants.new
    end

    def create
      @variant = @product.variants.new(variant_params)
      if @variant.save
        redirect_to admin_product_variants_path(@product)
      else
        flash[:error] = "创建失败：#{@product.errors.full_messages}"
        render :new
      end
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private

    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_variant
      @variant = @product.variants.find(params[:id])
    end

    def variant_params
      params[:variant].permit!
    end

  end
end

app/views/admin/variants/_form.html.erb
<%= form_for [:admin, @product, @variant] do |f| %>
  <% @product.option_types.each do |option_type| %>
    <label><%= option_type.name %></label>
    <%#= f.select :option_variant_value, options_from_collection_for_select(option_type.option_values, :name, :name) %>
    <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
                            { include_blank: true }, { name: 'variant[option_value_ids][]', class: 'select2' } %>
  <% end %>
  <label>价格</label>
  <%= f.text_field :price %>


  <button type="submit" class="btn btn-default">创建</button>
  <button type="reset" class="btn btn-default">取消</button>
<% end %>

app/views/admin/variants/_variant.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <table width="100%" class="table table-striped table-bordered table-hover" id="variants">
      <thead>
      <tr>
        <th>型号</th>
        <th>价格</th>
        <th>操作</th>
      </tr>
      </thead>
      <tbody>
      <% @variants.each do |variant| %>
        <tr>
          <td><%= variant.option_values.map { |option_value| "#{option_value.option_type.name}: #{option_value.name}" }.join(",") %></td>
          <td><%= variant.price %></td>
          <td>
            <%= link_to '编辑', edit_admin_product_variant_path(@product, variant) %> |
            <%= link_to '删除', admin_product_variants_path(variant), method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/variants/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">具体型号</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-9">
            <%= render 'form' %>
          </div>
          <div class="col-lg-3">
            <%= render 'admin/shared/product_sidebar' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/variants/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">具体型号</h1>
      <%= link_to '新建型号', new_admin_product_variant_path %>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-9">
            <%= render 'variant' %>
          </div>
          <div class="col-lg-3">
            <%= render 'admin/shared/product_sidebar' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/variants/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">具体型号</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-9">
            <%= render 'form' %>
          </div>
          <div class="col-lg-3">
            <%= render 'admin/shared/product_sidebar' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->