config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'admin/', class_name: 'Admin::User', controllers: {sessions: 'admin/sessions'}
  root to: 'admin/orders#index'
  namespace :admin do

    resources :products do
      resources :product_properties
      resources :variants
    end
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :complete
      end
    end
    resources :banners
    resources :option_types
    resources :prototypes do
      member do
        get :get_property_names
      end
    end
    resources :feedbacks

    require 'sidekiq/web'
    require 'sidekiq-status/web'
    authenticate :admin_user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount API, at: '/api'
end

app/models/product.rb
class Product < ApplicationRecord

  before_destroy :ensure_no_line_items

  has_one :master,
          -> { where is_master: true },
          inverse_of: :product,
          class_name: 'Variant'

  has_many :variants,
           -> { where(is_master: false).order(:position) },
           inverse_of: :product,
           class_name: 'Variant'

  has_many :variants_including_master,
           -> { order(:position) },
           inverse_of: :product,
           class_name: 'Variant',
           dependent: :destroy

  has_many :variant_images, -> { order(:position) }, source: :images, through: :variants_including_master
  [
      :sku, :price, :currency, :weight, :height, :width, :depth, :is_master,
      :cost_currency, :price_in, :amount_in, :cost_price, :images
  ].each do |method_name|
    delegate method_name, :"#{method_name}=", to: :find_or_build_master
  end

  has_many :product_option_types, dependent: :destroy, inverse_of: :product
  has_many :option_types, through: :product_option_types

  has_many :product_properties, dependent: :destroy, inverse_of: :product
  has_many :properties, through: :product_properties
  accepts_nested_attributes_for :product_properties, :allow_destroy => true

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  has_one :product_brand, dependent: :destroy
  has_one :brand, through: :product_brand

  scope :available, -> { where(available: true) }

  # after_create :add_associations_from_prototype
  after_save :save_master

  def find_or_build_master
    master || build_master
  end

  # there's a weird quirk with the delegate stuff that does not automatically save the delegate object
  # when saving so we force a save using a hook
  # Fix for issue #5306
  def save_master
    master.save!
  end

  # Adding properties and option types on creation based on a chosen prototype
  attr_reader :prototype_id
  def prototype_id=(value)
    @prototype_id = value.to_i
  end

  private
  # def add_associations_from_prototype
  #   if prototype_id && prototype = Prototype.find_by(id: prototype_id)
  #     prototype.properties.each do |property|
  #       product_properties.create(property: property)
  #     end
  #   end
  # end

  def ensure_no_line_items
    if line_items.any?
      errors.add(:base, :cannot_destroy_if_attached_to_line_items)
      throw(:abort)
    end
  end

end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    def new
      set_aliyun_upload
      @product = Product.new
      # @product_property = @product.product_properties.build
      # @properties = @product_property.build_property
    end

    def create
      begin
        @product = Product.new(product_params)
        if set_images && set_brand && @product.save
          redirect_to edit_admin_product_path(@product)
        else
          flash[:error] = "创建失败：#{@product.errors.full_messages}"
          render :new
        end
      end
    end

    def index
      @products = Product.order(created_at: :desc)
                      .includes(:brand)
                      .includes(:categories)
                      .includes(:master)
    end

    def show

    end

    def edit
      set_aliyun_upload
    end

    def update
      begin
        puts params
        puts "*****"
        puts params
        if set_images && set_brand && @product.update(product_params) && @product.save
          redirect_to admin_products_path
        else
          flash[:error] = "更新失败：#{@product.errors.full_messages}"
          redirect_to edit_admin_product_path(@product)
        end
      end
    end

    def destroy
      Product.transaction do
        LineItem.where(line_itemable_type: 'Cart', variant_id: @product.variants_including_master.map(&:id)).destroy_all
        @product.destroy
      end
      redirect_to admin_products_path
    end


    private
    def set_images
      if params[:images].present?
        @product.images.delete_all unless @product.new_record?
        params[:images].each do |image_url|
          @product.images << Image.create(url: image_url)
        end
      end
      true
    end
    def set_brand
      if params[:brand_id].present?
        brand = Brand.find(params[:brand_id])
        @product.brand = brand
      else
        true
      end
    end

    def set_product
      @product = Product.find(params[:id])
    end
    def product_params
      params[:product].permit!
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>

  <div class="form-group">
    <label>商品名称*</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>默认价格*</label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <% if @product.new_record? %>
    <div class="form-group">
      <label>原型</label>
      <%= f.select :prototype_id, content_tag(:option,'无',:value=>"") + options_from_collection_for_select(Prototype.all, :id, :name, @product.prototype_id) %>
    </div>
  <% end %>

  <% unless @product.new_record? %>
    <div class="form-group">
      <label>所属分类</label>
      <%= f.select :category_ids, nested_set_options(Category) {|i| "#{'-' * i.level} #{i.name}" }, {:include_blank => '无'} %>
    </div>
    <div class="form-group">
      <label>所属品牌</label>
      <%= select_tag :brand_id, options_from_collection_for_select(Brand.all, :id, :name, @product.brand.try(:id)), {:include_blank => '无'} %>
    </div>

    <div class="form-group">
      <label>商品简介</label>
      <%= f.text_area :description, class:"form-control", rows: "3" %>
    </div>

    <div class="form-group">
      <label>商品详情</label>
      <%= f.text_area :details, id: "editor", placeholder: "Balabala" %>
    </div>

    <div class="form-group">
      <label>商品图片</label>
      <input type="file" id="upload" multiple />
    </div>

    <div class="multiple_picture" name_value="images[]">
      <ul id="max-picture-number" class="edit_product_pictures clear-fix <%= 'data' unless @product.new_record? %>" max-picture-number="6">
        <% @product.images.each do |image| %>
          <li><input type="hidden" name="images[]" value="<%= image.url %>"/><img src="<%= image.full_url + '?x-oss-process=image/resize,w_150' %>" alt="图片说明"/><a class="hit_ajax delete" >删除</a></li>
        <% end %>
      </ul>
    </div>

    <div class="form-group">
      <label>规格选项</label>
      <%= f.select :option_type_ids, options_from_collection_for_select(OptionType.all, :id, :name, {:selected => @product.option_type_ids}), {include_hidden: false}, {class: 'select2', multiple: true} %>
    </div>
  <% end %>

  <div class="form-group">
    <label>上架</label>
    <label class="radio-inline">
      <input type="radio" name="product[available]" id="available_true" value="true" <%= 'checked="checked"' if @product.available == true %> >是
    </label>
    <label class="radio-inline">
      <input type="radio" name="product[available]" id="available_false" value="false" <%= 'checked="checked"' if @product.available == false %>>否
    </label>
  </div>
  <div class="form-group">
    <label>排序</label>
    <%= f.text_field :position, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-default"><%= @product.new_record? ? '创建' : '更新' %></button>
  <button type="reset" class="btn btn-default">取消</button>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= product.brand.try(:name) %></td>
  <td><%= product.price %></td>
  <td><%= product.available == true ? '是' : '否' %></td>
  <td><%= product.categories.map(&:name).join(",")%></td>
  <td><%= product.position %></td>
  <td>
    <%= link_to '编辑', edit_admin_product_path(product) %>
    <%= link_to '删除', admin_product_path(product), method: :delete %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">编辑商品</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-8">
            <%= render 'form' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/products/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <h1 class="page-header">商品列表
      <a href="<%= new_admin_product_path %>" style="float: right; padding-right: 15px;"><button type="button" class="btn btn-primary btn-lg">添加商品</button></a>
    </h1>

  </div>
  <!-- /.col-lg-12 -->
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">

        <!-- /.panel-heading -->
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="products">
            <thead>
            <tr>
              <th>ID</th>
              <th>商品名称</th>
              <th>品牌</th>
              <th>售价</th>
              <!--<th>库存</th>-->
              <th>上架</th>
              <th>分类</th>
              <th>排序</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: 'product', collection: @products %>
            </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->

</div>

app/views/admin/products/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">添加商品</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-8">
            <%= render 'form' %>
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/products/show.html.erb
<h1>Admin::Products#show</h1>
<p>Find me in app/views/admin/products/show.html.erb</p>