config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'admin/', class_name: 'Admin::User', controllers: {sessions: 'admin/sessions'}
  root to: 'admin/orders#index'
  namespace :admin do

    resources :products do
      resources :product_properties
      resources :variants
    end
    resources :categories
    resources :brands
    resources :orders do
      member do
        post :complete
      end
    end
    resources :banners
    resources :option_types
    resources :prototypes do
      member do
        get :get_property_names
      end
    end
    resources :feedbacks

    require 'sidekiq/web'
    require 'sidekiq-status/web'
    authenticate :admin_user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount API, at: '/api'
end

app/views/admin/shared/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="index.html">平昌养车-管理后台</a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">

      <li><%= link_to('注销', destroy_admin_user_session_path, method: :delete) %></li>
    </ul>
    <!-- /.dropdown-user -->
  </li>
  <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

app/views/admin/shared/_product_sidebar.html.erb
<div class="navbar-default" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <ul class="nav nav-second-level">
          <li>
            <a href="<%= edit_admin_product_path(@product) %>">详情</a>
          </li>
          <li>
            <a href="<%= admin_product_variants_path(@product) %>">具体型号</a>
          </li>
          <li>
            <a href="<%= admin_product_product_properties_path(@product) %>">属性</a>
          </li>
        </ul>
      </li>

    </ul>
  </div>
</div>

app/views/admin/shared/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <!--<li class="sidebar-search">-->
        <!--<div class="input-group custom-search-form">-->
          <!--<input type="text" class="form-control" placeholder="Search...">-->
          <!--<span class="input-group-btn">-->
                                <!--<button class="btn btn-default" type="button">-->
                                    <!--<i class="fa fa-search"></i>-->
                                <!--</button>-->
                            <!--</span>-->
        <!--</div>-->
        <!--&lt;!&ndash; /input-group &ndash;&gt;-->
      <!--</li>-->
      <li>
        <a href="/"><i class="fa fa-dashboard fa-fw"></i> 主页</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-table fa-fw"></i> 商品管理 <span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="<%= admin_products_path %>">商品列表</a>
          </li>
          <li>
            <a href="<%= admin_categories_path %>">商品分类</a>
          </li>
          <li>
            <a href="<%= admin_brands_path %>">品牌管理</a>
          </li>
          <li>
            <a href="<%= admin_banners_path %>">轮播列表</a>
          </li>
          <li>
            <a href="<%= admin_prototypes_path %>">原型管理</a>
          </li>
          <li>
            <a href="<%= admin_option_types_path %>">型号选项</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="tables.html"><i class="fa fa-table fa-fw"></i> 订单中心<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="<%= admin_orders_path %>">订单列表</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="tables.html"><i class="fa fa-table fa-fw"></i> 意见箱<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="<%= admin_feedbacks_path %>">反馈列表</a>
          </li>
        </ul>
      </li>
      <!--<li>-->
        <!--<a href="forms.html"><i class="fa fa-edit fa-fw"></i> 会员管理</a>-->
      <!--</li>-->
    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->